# Generated by Django 3.2.12 on 2022-08-31 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_kullanici'),
    ]

    operations = [
        migrations.AddField(
            model_name='kullanici',
            name='email',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
