# Generated by Django 3.2.12 on 2022-08-31 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_kullanici_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kullanici',
            old_name='dogum',
            new_name='date',
        ),
    ]
