# Generated by Django 3.2.12 on 2022-08-31 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_rename_dogum_kullanici_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kullanici',
            name='date',
        ),
    ]
